#!/usr/bin/env ruby

require 'kontena/etcd'

Kontena::Etcd::Model.etcd = Kontena::Etcd::Client.from_env

require_relative 'kontena-etcd-model'

Example.delete

Example.create('foo1', bar: 'bar2')

Example.each do |example|
  puts "#{example.foo}=#{example.bar}"
end

example = Example.get('foo1')
